/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sgrs;

/**
 *
 * @author Gustavo
 */

import com.mycompany.sgrs.Sala;
import com.mycompany.sgrs.Usuario;
import com.mycompany.sgrs.Professor;
import com.mycompany.sgrs.Tecnico;
import com.mycompany.sgrs.Aluno;
import com.mycompany.sgrs.SalaDAO;
import com.mycompany.sgrs.UsuarioDAO;
import com.mycompany.sgrs.Reserva;
import com.mycompany.sgrs.ReservaDAO;
import com.mycompany.sgrs.Conexao;
import com.mycompany.sgrs.Professor;
import com.mycompany.sgrs.Reserva;
import com.mycompany.sgrs.ReservaDAO;
import com.mycompany.sgrs.Sala;
import com.mycompany.sgrs.SalaDAO;
import com.mycompany.sgrs.Tecnico;
import com.mycompany.sgrs.Usuario;
import com.mycompany.sgrs.UsuarioDAO;
import java.awt.Component;
import java.awt.GridLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;




public class Interface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface.class.getName());

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        carregarRelatorioSalasMaisReservadas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        boolAluno = new javax.swing.JCheckBox();
        boolProfessor = new javax.swing.JCheckBox();
        boolTecnico = new javax.swing.JCheckBox();
        txtNomeUsuario = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        buttonCadastro = new javax.swing.JButton();
        buttonLimpar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        boolAtivo = new javax.swing.JCheckBox();
        boolInativo = new javax.swing.JCheckBox();
        txtEquipamentos = new javax.swing.JTextField();
        txtCapacidade = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtSala = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtFim = new javax.swing.JFormattedTextField();
        txtInicio = new javax.swing.JFormattedTextField();
        txtData = new javax.swing.JTextField();
        txtMatriculaUsuario = new javax.swing.JTextField();
        buttonReserva = new javax.swing.JButton();
        buttonCancelarReserva = new javax.swing.JButton();
        txtSalabusca = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtMatriculaBusca = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCancelamentoReservas = new javax.swing.JTable();
        screamTelaRelatorios = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        Salasmaisreservadas = new javax.swing.JScrollPane();
        tblTelasMaisReservadas = new javax.swing.JTable();
        Reservasfuturas = new javax.swing.JScrollPane();
        tblReservasFuturas = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtBuscarReservarRelatorio = new javax.swing.JTextField();
        buttonBuscarReservas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dados Pessoais");

        jLabel2.setText("Nome Completo:");

        jLabel3.setText("Matrícula:");

        jLabel4.setText("Tipo de Usuário: ");

        boolAluno.setText("Aluno");
        boolAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boolAlunoActionPerformed(evt);
            }
        });

        boolProfessor.setText("Professor");

        boolTecnico.setText("Técnico");

        txtNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeUsuarioActionPerformed(evt);
            }
        });

        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });

        buttonCadastro.setText("Cadastrar Usuário");
        buttonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastroActionPerformed(evt);
            }
        });

        buttonLimpar.setText("Limpar Campos");
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparActionPerformed(evt);
            }
        });

        jLabel5.setText("Somente Números");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(boolAluno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boolProfessor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boolTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 492, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(buttonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtMatricula)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel5)))
                                        .addGap(108, 108, 108))))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(boolAluno)
                    .addComponent(boolProfessor)
                    .addComponent(boolTecnico))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCadastro)
                    .addComponent(buttonLimpar))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro de Usuário", jPanel1);

        jLabel6.setText("Identificação da Sala");

        jLabel7.setText("Nome da Sala: ");

        jLabel8.setText("Capacidade:");

        jLabel9.setText("Equipamentos: ");

        jLabel10.setText("Status:");

        boolAtivo.setText("Ativo");

        boolInativo.setText("Inativo");
        boolInativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boolInativoActionPerformed(evt);
            }
        });

        txtCapacidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapacidadeActionPerformed(evt);
            }
        });

        jLabel11.setText("Apenas Números");

        jButton1.setText("Cadastrar Sala");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpar Campos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel26.setText("Separado por \",\"");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(64, 64, 64)
                                .addComponent(boolAtivo)
                                .addGap(44, 44, 44)
                                .addComponent(boolInativo))
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(20, 20, 20)
                                .addComponent(txtSala, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 177, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCapacidade)
                            .addComponent(txtEquipamentos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel26))
                        .addGap(188, 188, 188))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel6)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtEquipamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)))
                    .addComponent(jLabel11))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(boolAtivo)
                    .addComponent(boolInativo))
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro Sala", jPanel2);

        jLabel12.setText("Dados de Reserva");

        jLabel13.setText("Matrícula do Usuário: ");

        jLabel14.setText("Sala:");

        jLabel15.setText("Data de Reserva");

        jLabel16.setText("Horário de Início:");

        jLabel17.setText("Horário de Término: ");

        txtFim.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFimActionPerformed(evt);
            }
        });

        txtInicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInicioActionPerformed(evt);
            }
        });

        txtMatriculaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaUsuarioActionPerformed(evt);
            }
        });

        buttonReserva.setText("Confirmar Reserva");
        buttonReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReservaActionPerformed(evt);
            }
        });

        buttonCancelarReserva.setText("Cancelar");
        buttonCancelarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarReservaActionPerformed(evt);
            }
        });

        jLabel18.setText("Digite nome da Sala");

        jLabel19.setText("yyyy-mm-dd");

        jLabel20.setText("hh:mm");

        jLabel21.setText("Apenas Números");

        jLabel22.setText("hh:mm");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(buttonReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonCancelarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMatriculaUsuario)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtSalabusca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(16, 16, 16)
                                                .addComponent(jLabel22)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel17)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtFim, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel20))
                                            .addComponent(txtData, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel21))))
                        .addGap(73, 73, 73))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel12)
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtMatriculaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(txtFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonReserva)
                            .addComponent(buttonCancelarReserva)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSalabusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reservas de Sala", jPanel3);

        jLabel23.setText("Busca por Matrícula");

        jLabel24.setText("Matrícula:");

        txtMatriculaBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaBuscaActionPerformed(evt);
            }
        });

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel25.setText("Reservas Futuras");

        tblCancelamentoReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Sala", "Data", "Inserir", "Fim", "Cancelar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCancelamentoReservas);
        tblCancelamentoReservas.getAccessibleContext().setAccessibleDescription("");
        tblCancelamentoReservas.getAccessibleContext().setAccessibleParent(jPanel4);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel25)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(31, 31, 31)
                        .addComponent(txtMatriculaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel23))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel23)
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtMatriculaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(47, 47, 47)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cancelamento de Reservas", jPanel4);

        jLabel27.setText("Salas Mais Reservadas");

        tblTelasMaisReservadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Sala", "Quantidade de Reservas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Salasmaisreservadas.setViewportView(tblTelasMaisReservadas);

        tblReservasFuturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sala", "Data", "Início", "Fim"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Reservasfuturas.setViewportView(tblReservasFuturas);

        jLabel28.setText("Reservas Futuras de um Usuário");

        jLabel29.setText("Matrícula:");

        txtBuscarReservarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarReservarRelatorioActionPerformed(evt);
            }
        });

        buttonBuscarReservas.setText("Buscar");
        buttonBuscarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarReservasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout screamTelaRelatoriosLayout = new javax.swing.GroupLayout(screamTelaRelatorios);
        screamTelaRelatorios.setLayout(screamTelaRelatoriosLayout);
        screamTelaRelatoriosLayout.setHorizontalGroup(
            screamTelaRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(screamTelaRelatoriosLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(screamTelaRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(screamTelaRelatoriosLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscarReservarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonBuscarReservas, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                    .addComponent(jLabel28)
                    .addComponent(Reservasfuturas)
                    .addComponent(jLabel27)
                    .addComponent(Salasmaisreservadas))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        screamTelaRelatoriosLayout.setVerticalGroup(
            screamTelaRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(screamTelaRelatoriosLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Salasmaisreservadas, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(screamTelaRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtBuscarReservarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscarReservas))
                .addGap(18, 18, 18)
                .addComponent(Reservasfuturas, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Tela de Relatórios", screamTelaRelatorios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void boolAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boolAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boolAlunoActionPerformed

    private void buttonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastroActionPerformed
    try {
            String nome = txtNomeUsuario.getText();
            String matricula = txtMatricula.getText();

            if (nome.trim().isEmpty() || matricula.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nome e Matrícula são obrigatórios.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if ((boolAluno.isSelected()&& boolProfessor.isSelected()) 
                    || (boolAluno.isSelected()&& boolTecnico.isSelected())
                    || (boolTecnico.isSelected()&& boolProfessor.isSelected())){
                JOptionPane.showMessageDialog(this, "Selecione apenas um item dos cargos Tecnicos.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Usuario novoUsuario = null;
            if (boolAluno.isSelected()) {
                novoUsuario = new Aluno(nome, matricula);
            } else if (boolProfessor.isSelected()) {
                novoUsuario = new Professor(nome, matricula);
            } else if (boolTecnico.isSelected()) {
                novoUsuario = new Tecnico(nome, matricula);
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um Tipo de Usuário.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
                return;
            }

            UsuarioDAO usuarioDAO = new UsuarioDAO();
            usuarioDAO.salvar(novoUsuario);

            JOptionPane.showMessageDialog(this, "Usuário cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);


        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro ao cadastrar o usuário:\n" + e.getMessage(), "Erro Inesperado", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCadastroActionPerformed

    private void txtNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeUsuarioActionPerformed

    private void boolInativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boolInativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boolInativoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
            String nome = txtSala.getText(); // Usando os nomes sugeridos
            int capacidade = Integer.parseInt(txtCapacidade.getText());
            String equipamentosInput = txtEquipamentos.getText();
            boolean ativa = boolAtivo.isSelected();


            List<String> equipamentos = Arrays.asList(equipamentosInput.split("\\s*,\\s*"));

            Sala novaSala = new Sala(nome, capacidade, equipamentos, ativa);

            SalaDAO salaDAO = new SalaDAO();
            salaDAO.salvar(novaSala);

            JOptionPane.showMessageDialog(this, "Sala cadastrada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);


        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "O campo 'Capacidade' deve conter apenas números.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro ao salvar a sala:\n" + e.getMessage(), "Erro Inesperado", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); 
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFimActionPerformed

    private void txtInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInicioActionPerformed

    private void buttonReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReservaActionPerformed
        try {
            String matricula = txtMatriculaUsuario.getText().trim();
            String nomeSala = txtSalabusca.getText().trim();
            String data = txtData.getText().trim(); 
            String horaInicio = txtInicio.getText().trim(); 
            String horaFim = txtFim.getText().trim(); 
            
            if (!data.matches("\\d{4}-\\d{2}-\\d{2}")) {
                JOptionPane.showMessageDialog(null, "Data inválida. Use o formato YYYY-MM-DD.");
                return;
            }
            if (!horaInicio.matches("\\d{2}:\\d{2}") || !horaFim.matches("\\d{2}:\\d{2}")) {
                JOptionPane.showMessageDialog(null, "Horário inválido. Use o formato HH:mm.");
                return;
            }
            
            if (matricula.isEmpty() || nomeSala.isEmpty() || data.isEmpty() || horaInicio.isEmpty() || horaFim.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios.");
                return;
            }

            UsuarioDAO usuarioDAO = new UsuarioDAO();
            SalaDAO salaDAO = new SalaDAO();
            ReservaDAO reservaDAO = new ReservaDAO();

            Optional<Usuario> usuarioOpt = usuarioDAO.buscarPorMatricula(matricula);
            if (usuarioOpt.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Usuário não encontrado.");
                return;
            }
            Usuario usuario = usuarioOpt.get();

            Sala sala = salaDAO.buscarPorNome(nomeSala);
            if (sala == null || !sala.isAtiva()) {
                JOptionPane.showMessageDialog(null, "Sala não encontrada ou inativa.");
                return;
            }

            boolean conflito = reservaDAO.verificarConflito(sala.getId(), data, horaInicio, horaFim);
            if (conflito) {
                JOptionPane.showMessageDialog(null, "Já existe uma reserva para essa sala nesse horário.");
                return;
            }

            Reserva reserva = new Reserva();
            reserva.setIdUsuario(usuario.getId());
            reserva.setIdSala(sala.getId());
            reserva.setDataReserva(data);
            reserva.setHoraInicio(horaInicio);
            reserva.setHoraFim(horaFim);
            reserva.setStatus("Confirmada");

            reservaDAO.salvar(reserva);

            JOptionPane.showMessageDialog(null, "Reserva realizada com sucesso!");

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao realizar reserva: " + e.getMessage());
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_buttonReservaActionPerformed

    private void txtMatriculaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaUsuarioActionPerformed

    private void txtMatriculaBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaBuscaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String matricula = txtMatriculaBusca.getText().trim();
    if (matricula.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Informe a matrícula.");
        return;
    }

 
    DefaultTableModel model = new DefaultTableModel(
        new Object[][] {},
        new String[] {"ID", "Sala", "Data", "Início", "Fim", "Ação"}
    ) {
        @Override
        public Class<?> getColumnClass(int columnIndex) {
            return String.class; 
        }
        @Override
        public boolean isCellEditable(int row, int col) {
            return col == 5; 
        }
    };
    tblCancelamentoReservas.setModel(model);

    try {
        Optional<Usuario> uOpt = new UsuarioDAO().buscarPorMatricula(matricula);
        if (uOpt.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Usuário não encontrado.");
            return;
        }
        int idUsuario = uOpt.get().getId();

        List<Reserva> reservas = new ReservaDAO().listarReservasFuturas(idUsuario);

        for (Reserva r : reservas) {
            model.addRow(new Object[]{
                String.valueOf(r.getId()),
                r.getStatus(),           
                r.getDataReserva(),
                r.getHoraInicio(),
                r.getHoraFim(),
                "Cancelar"
            });
        }
    

        model.fireTableDataChanged();

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Erro ao buscar reservas: " + ex.getMessage());
    } 
    TableColumn acaoColuna = tblCancelamentoReservas.getColumnModel().getColumn(5);
        acaoColuna.setCellRenderer(new TableCellRenderer() {
            private final JButton button = new JButton("Cancelar");

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                return button;
            }
        });

        acaoColuna.setCellEditor(new DefaultCellEditor(new JCheckBox()) {
            private final JButton button = new JButton("Cancelar");

            {
                button.addActionListener(e -> {
                    int row = tblCancelamentoReservas.getSelectedRow();
                    int idReserva = Integer.parseInt(tblCancelamentoReservas.getValueAt(row, 0).toString());
                    int confirma = JOptionPane.showConfirmDialog(null, "Confirma cancelar esta reserva?", "Confirmar", JOptionPane.YES_NO_OPTION);
                    if (confirma == JOptionPane.YES_OPTION) {
                        try {
                            new ReservaDAO().cancelarReserva(idReserva);
                            ((DefaultTableModel) tblCancelamentoReservas.getModel()).removeRow(row);
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(null, "Falha ao cancelar: " + ex.getMessage());
                        }
                    }
                });
            }

            @Override
            public Component getTableCellEditorComponent(JTable table, Object value,
                    boolean isSelected, int row, int column) {
                return button;
            }

            @Override
            public Object getCellEditorValue() {
                return "Cancelar";
            }
        });
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtBuscarReservarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarReservarRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarReservarRelatorioActionPerformed

    private void buttonBuscarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarReservasActionPerformed
        String matricula = txtBuscarReservarRelatorio.getText().trim();
        if (matricula.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe a matrícula.");
            return;
        }

        try {
            Optional<Usuario> usuario = new UsuarioDAO().buscarPorMatricula(matricula);
            if (usuario.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Usuário não encontrado.");
                return;
            }

            List<Reserva> reservas = new ReservaDAO().listarReservasFuturas(usuario.get().getId());

            DefaultTableModel modelo = (DefaultTableModel) tblReservasFuturas.getModel();
            modelo.setRowCount(0);
            for (Reserva r : reservas) {
                modelo.addRow(new Object[] {
                    r.getStatus(), 
                    r.getDataReserva(),
                    r.getHoraInicio(),
                    r.getHoraFim()
                });
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar reservas: " + ex.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBuscarReservasActionPerformed

    private void buttonCancelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarReservaActionPerformed
        limparCamposReserva();      // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelarReservaActionPerformed

    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
        limparCamposUsuario();        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLimparActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limparCamposSala();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtCapacidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidadeActionPerformed
    
    private void tblCancelamentoReservasMouseClicked(java.awt.event.MouseEvent evt) {
    int row = tblCancelamentoReservas.rowAtPoint(evt.getPoint());
    int col = tblCancelamentoReservas.columnAtPoint(evt.getPoint());
    if (col == 5) { // coluna do botão
        int idReserva = (int) tblCancelamentoReservas.getValueAt(row, 0);
        int confirma = JOptionPane.showConfirmDialog(this, "Confirma cancelar esta reserva?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            try {
                new ReservaDAO().cancelarReserva(idReserva);
                ((DefaultTableModel) tblCancelamentoReservas.getModel()).removeRow(row);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Falha ao cancelar: " + ex.getMessage());
            }
        }
    }
}
        private void carregarRelatorioSalasMaisReservadas() {
        try {
            List<Object[]> salasMaisReservadas = new ReservaDAO().buscarSalasMaisReservadas();

            DefaultTableModel modelo = (DefaultTableModel) tblTelasMaisReservadas.getModel();
            modelo.setRowCount(0);
            for (Object[] linha : salasMaisReservadas) {
                modelo.addRow(linha); 
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar salas mais reservadas: " + ex.getMessage());
        }
    }
        
    private void limparCamposSala() {
        txtSala.setText("");
        txtCapacidade.setText("");
        txtEquipamentos.setText("");
    }
      private void limparCamposUsuario() {
        txtNomeUsuario.setText("");
        txtMatricula.setText("");
    }

        private void limparCamposReserva() {
         txtMatriculaUsuario.setText("");
         txtData.setText("");
         txtInicio.setText("");
         txtFim.setText("");
         txtSalabusca.setText("");
     }
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface().setVisible(true));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Reservasfuturas;
    private javax.swing.JScrollPane Salasmaisreservadas;
    private javax.swing.JCheckBox boolAluno;
    private javax.swing.JCheckBox boolAtivo;
    private javax.swing.JCheckBox boolInativo;
    private javax.swing.JCheckBox boolProfessor;
    private javax.swing.JCheckBox boolTecnico;
    private javax.swing.JButton buttonBuscarReservas;
    private javax.swing.JButton buttonCadastro;
    private javax.swing.JButton buttonCancelarReserva;
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JButton buttonReserva;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel screamTelaRelatorios;
    private javax.swing.JTable tblCancelamentoReservas;
    private javax.swing.JTable tblReservasFuturas;
    private javax.swing.JTable tblTelasMaisReservadas;
    private javax.swing.JTextField txtBuscarReservarRelatorio;
    private javax.swing.JTextField txtCapacidade;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtEquipamentos;
    private javax.swing.JFormattedTextField txtFim;
    private javax.swing.JFormattedTextField txtInicio;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtMatriculaBusca;
    private javax.swing.JTextField txtMatriculaUsuario;
    private javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JTextField txtSala;
    private javax.swing.JTextField txtSalabusca;
    // End of variables declaration//GEN-END:variables
}
